#
###################################
# Site wide configuration
####################################
#
title: 枫林渡
email: zhangjusuo@gmail.com
description: 汇集资讯文章，整理技术心得。
url: https://mapleferry.github.io # the base hostname & protocol for your site
keywords: ["资讯", "编程", "经验"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jones
  avatar: mf-logo.png
  job: "产品经理，Java工程师，Python爱好者"
  bio: "生活工作在北京，喜欢研究学习新技术，爱好旅游、运动"
  email: zhangjusuo@gmail.com
  disqus-shortname: mapleferry
  twitter: zhangjusuo #username
  #facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: mapleferry #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  #linkedin: renyuan-zou-69b7038a #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
