name: Deploy Hugo site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.145.0
    steps:
      - name: Install Hugo CLI
        run: |
          echo ">>> 开始安装Hugo CLI..."
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
          echo "<<< Hugo CLI安装完成"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup theme
        run: |
          echo ">>> 开始设置主题..."
          if [ ! -d "themes/PaperMod" ]; then
            echo ">>> 主题目录不存在，开始克隆主题..."
            mkdir -p themes
            git clone --depth=1 https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
            echo "<<< 主题克隆完成"
          else
            echo ">>> 主题目录已存在，显示内容："
            ls -la themes/PaperMod
          fi
          echo "<<< 主题设置完成"
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Pre-build check
        run: |
          echo ">>> 开始构建前检查..."
          echo ">>> 当前目录结构："
          find . -maxdepth 3 -type d | sort
          echo ">>> 主题配置："
          ls -la themes/PaperMod/
          echo ">>> 内容目录："
          ls -la content/
          echo "<<< 构建前检查完成"

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: |
          echo ">>> 查看Hugo版本信息："
          hugo version
          echo ">>> 打印Hugo配置信息："
          hugo config | grep -i "theme\|baseurl\|publishdir"
          echo ">>> 开始Hugo构建..."
          hugo \
            --gc \
            --minify \
            --baseURL="${{ steps.pages.outputs.base_url }}"
          echo "<<< Hugo构建完成"

      - name: Debug output
        run: |
          echo ">>> 开始调试输出..."
          echo ">>> 检查站点结构："
          ls -la public/
          echo ">>> 检查CSS目录："
          ls -la public/css/ || echo "No CSS directory found"
          echo ">>> 检查index HTML："
          head -n 20 public/index.html || echo "No index.html found"
          echo ">>> 检查配置文件："
          cat config.yaml
          echo ">>> 检查主题结构："
          ls -la themes/PaperMod/layouts/
          echo ">>> 当前目录结构："
          find . -maxdepth 2 -type d | sort
          echo "<<< 调试输出完成"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4